M48
; DRILL file {KiCad 8.0.4-8.0.4-0~ubuntu24.04.1} date 2024-07-31T18:59:32-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-31T18:59:32-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4-8.0.4-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X5.2499Y-4.2862
X5.2499Y-4.5138
M30
